version: "3.8"

services:
  netdaemon:
    container_name: homeassistant-netdaemon
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      Tibber__Token: "${TIBBER_TOKEN}"
      HomeAssistant__Host: "${HOMEASSISTANT_HOST}"
      HomeAssistant__Token: "${HOMEASSISTANT_TOKEN}"
      TZ: "${TZ}"
      DOTNET_ENVIRONMENT: "${DOTNET_ENVIRONMENT}"
    tty: true
    stdin_open: true
    restart: unless-stopped
    labels:
      - "com.docker.compose.service=netdaemon"
      - "logging.service=netdaemon"
      - "monitoring.stack=homeassistant"
      - "logging.promtail=true"
      - "logging.job=homeassistant-netdaemon"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
